const express = require('express')
const app = express()
const router = require('./routers/index')
const bodyParser = require('body-parser')
app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.use(router)
app.set('view engine', 'ejs')
app.set('views', __dirname+'/views/html')
app.use('static', express.static(__dirname+'/views'))
app.listen(5000, function(){
    console.log('listened')
})